[package]
name = "outbox-postgres"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
sqlx.workspace = true
async-trait.workspace = true
outbox-core = { path="../outbox-core", features = ["sqlx"] }

tokio.workspace = true
rstest.workspace = true
testcontainers.workspace = true
testcontainers-modules.workspace = true
tracing.workspace = true

uuid.workspace = true